### ISSUE TITLE
Nothing happens on switching project

### ISSUE THREAD

**Issue by Demianeen** [imNel/monorepo.nvim#10]
I managed to add projects, but I don't know if switching between projects does something. Take a look:
https://github.com/imNel/monorepo.nvim/assets/51330172/f61faeed-6c8b-489a-a359-b046452760ee

Is it doing something and I don't see it?

**Comment by imNel** [comment]
If you run something like `:Telescope find_files` or `:Telescope live_grep` the results should be scoped to the subproject :)

The most basic thing that should change is `:pwd`

**Comment by Demianeen** [comment]
Thanks for the explanation!
Lazyvim has it's own telescope search directory [modification](https://github.com/LazyVim/LazyVim/blob/c433ea7aa842c446edc2b1570998bf5440c68188/lua/lazyvim/util/telescope.lua#L15-L51), so I think that's why it wasn't working.
