### ISSUE TITLE
Custom name

### ISSUE THREAD

**Issue by jin-ahn** [imNel/monorepo.nvim#6]
I have multiple projects in the same repo where the code base is "project1/src" "project2/src". At the "project1" level there's only package.json, node_modules, etc. Under source is where all the .ts files are. If i try to add a project at the "project1" level this plugin returns error saying I am not in a project. If I add it at the "src" level, it does get added but now all my projects are labeled "src". Is there a way to give it a custom name or force it add a project at the "project1" folder level?

**Comment by imNel** [comment]
Hey, not sure what you mean by this. If open neovim in the root of your monorepo, you can add the two projects and swap between them.

The workflow should be:
1. `cd ~/monorepo`
2. `nvim`
3. Add `project1/src`
4. Add `project2/src`
5. Then you have 3 options: `/`, `/project1/src` and `/project2/src`
