### ISSUE TITLE
Doesn't seem to work well with sessions

### ISSUE THREAD

**Issue by Ciel-MC** [imNel/monorepo.nvim#7]
When I use monorepo with sessions, the base dir seems to have been lost after reloading the session, making sessions and monorepo mutually exclusive...

**Comment by imNel** [comment]
Hi @Ciel-MC, Sorry for the long wait, I've been busy! 

I've added a fix for this in https://github.com/imNel/monorepo.nvim/commit/256a302900d6af6e032f1f2bf4f2407bd4569fe8. It's fairly simple and only works if your session is the base monorepo, but it's better than nothing.

Here is some code you can throw in your config if you don't want to update :)
```lua
vim.api.nvim_create_autocmd("SessionLoadPost", {
  callback = function()
    require("monorepo").change_monorepo(vim.fn.getcwd())
  end,
})
```

I will note though that you can probably get more granularity by using a some sort of pre hook when making a session. Pugins might expose this for you but if you're doing it manually you'll need to swap back to root before running `:mksession`.

**Comment by imNel** [comment]
Closing, feel free to reopen if you need anything else :)

**Comment by Ciel-MC** [comment]
Sorry for getting back so late lol, I abandoned the monorepo so I didn't look deeper. But I was wondering if there is already a function to switch back to root, so I can actually make a hook? Perhaps a switch function that takes the relative path(to switch to "/"), or just a variable exposing the root dir? I think I can just switch to no. 1, but I'm actually not sure if that will always be "/"
